### ISSUE TITLE
eslint does not recognize the plugin

### ISSUE THREAD

**Issue by cobraz** [pulumi/eslint-plugin-pulumi#9]
### What happened?

The package is exported with source files, a package .tgz file and no `dist` files.

This causes the package not to be recognized by eslint.

See here:
https://www.runpkg.com/?@pulumi/eslint-plugin@0.1.0-rc1/src/index.ts	

### Steps to reproduce

yarn install @pulumi/eslint-plugin

### Expected Behavior

I expect it to be recognized with `eslint`, and probably with no source files?

### Actual Behavior

The package is exported with source files, a package .tgz file and no `dist` files.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cobraz** [comment]
I'd love to help, but there's a lot of code here for publishing that I don't know (yet). I'd love to get a run-through of it :)

**Comment by kpitzen** [comment]
Hi @cobraz !  Thanks for opening this issue - for now, since we're still very much in pre-release territory, you'll need to specify in `package.json` that you want `0.1.0-rc3`.  It's not published as `latest` so yarn isn't picking it up by default.  As soon as we ship the next release, this will be resolved :)
